[package]
name = "3cc"
version = "0.1.0"
authors = ["alex"]
edition = "2018"
license = "GPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snafu = "*"
itertools = "*"
