name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: textbook/git-checkout-submodule-action@2.0.0
    - name: Update Rust stable
      run: rustup toolchain update --no-self-update stable
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: |
        cd test_cases
        bash test_compiler.sh ../target/debug/3cc 1 2 3 4 5
 #   - name: Run tests
   #   run: cargo test --verbose
       
